config/routes.rb
Rails.application.routes.draw do
  resources :relations

  get 'home_link/home'

  get 'algorithm/index'

  get 'algorithms/index'

  resources :algorithms

	resources :tags

  root :to => 'algorithm#index', :as => 'index'
	get "home" => "home_link#home"

end

app/models/algorithm.rb
class Algorithm < ActiveRecord::Base
	ALGORITHM_LANGUAGES=["pseudoCode","Python","Cpp","Java","Ruby"]
  acts_as_taggable
	validates :name, :description, :link, :author, presence: true
	#ensure each algorithm has a unique name
	validates :name, uniqueness: true
	validates :difficulty, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 10}
	validates :link, allow_blank: true, format: {
  		with: %r{\.(gif|jpg|png|jpeg)\Z}i,
  		message: 'must be a URL for GIF, JPG or dirPNG image.'
	}
	def self.searchbar(search)
		where("name LIKE ?", "%#{search}%") 
	end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :algorithm
  belongs_to :inventor
end

app/controllers/algorithm_controller.rb
class AlgorithmController < ApplicationController
  def index
    if params[:search]
      empty_search = false
#params[:search].keep_if {|k, val| !val.blank?}.empty?
    else
      empty_search = true
    end
    if empty_search
     @algorithms=Algorithm.all
    else
     # a search was submitted
     @searchval = Algorithm.searchbar(params[:search])
     @algorithms = @searchval.all
    end
	end
end

app/controllers/algorithms_controller.rb
class AlgorithmsController < ApplicationController
  before_action :set_algorithm, only: [:show, :edit, :update, :destroy]

  # GET /algorithms
  # GET /algorithms.json
  def index
    @algorithms=Algorithm.all
  end

  # GET /algorithms/1
  # GET /algorithms/1.json
  def show

  end

  # GET /algorithms/new
  def new
    @algorithm = Algorithm.new
		#@inventors = Inventor.all
  end

  # GET /algorithms/1/edit
  def edit
  end

  # POST /algorithms
  # POST /algorithms.json
  def create
    @algorithm = Algorithm.new(algorithm_params)
    respond_to do |format|
      if @algorithm.save
        format.html { redirect_to @algorithm, notice: 'Algorithm was successfully created.' }
        format.json { render :show, status: :created, location: @algorithm }
      else
        format.html { render :new }
        format.json { render json: @algorithm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /algorithms/1
  # PATCH/PUT /algorithms/1.json
  def update
    respond_to do |format|
      if @algorithm.update(algorithm_params)
        format.html { redirect_to @algorithm, notice: 'Algorithm was successfully updated.' }
        format.json { render :show, status: :ok, location: @algorithm }
      else
        format.html { render :edit }
        format.json { render json: @algorithm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /algorithms/1
  # DELETE /algorithms/1.json
  def destroy
    @algorithm.destroy
    respond_to do |format|
      format.html { redirect_to algorithms_url, notice: 'Algorithm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_algorithm
      @algorithm = Algorithm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def algorithm_params
      params.require(:algorithm).permit(:name, :purpose, :description, :link, :pseudoCode, :complexityAnalysis, :difficulty, :author, :tag_list)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_link_controller.rb
class HomeLinkController < ApplicationController
  def home
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def show
  end
end

app/controllers/relations_controller.rb
class RelationsController < ApplicationController
  before_action :set_relation, only: [:show, :edit, :update, :destroy]

  # GET /relations
  # GET /relations.json
  def index
    @relations = Relation.all
  end

  # GET /relations/1
  # GET /relations/1.json
  def show
  end

  # GET /relations/new
  def new
    @relation = Relation.new
  end

  # GET /relations/1/edit
  def edit
  end

  # POST /relations
  # POST /relations.json
  def create
    @relation = Relation.new(relation_params)

    respond_to do |format|
      if @relation.save
        format.html { redirect_to @relation, notice: 'Relation was successfully created.' }
        format.json { render :show, status: :created, location: @relation }
      else
        format.html { render :new }
        format.json { render json: @relation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /relations/1
  # PATCH/PUT /relations/1.json
  def update
    respond_to do |format|
      if @relation.update(relation_params)
        format.html { redirect_to @relation, notice: 'Relation was successfully updated.' }
        format.json { render :show, status: :ok, location: @relation }
      else
        format.html { render :edit }
        format.json { render json: @relation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relations/1
  # DELETE /relations/1.json
  def destroy
    @relation.destroy
    respond_to do |format|
      format.html { redirect_to relations_url, notice: 'Relation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relation
      @relation = Relation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def relation_params
      params.require(:relation).permit(:algorithms_id, :inventor)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	before_action :set_tag, only: [:show, :edit, :update]
  def index
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    #@tag =  ActsAsTaggableOn::Tag.find(params[:id])
    @algorithms = Algorithm.tagged_with(@tag.name)
  end

	def edit
  end
	def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to tag_url(@tag), notice: 'Algorithm was successfully updated.' }
        format.json { render :show, status: :ok, location: @algorithm }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag =  ActsAsTaggableOn::Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:acts_as_taggable_on_tag).permit(:name,:description)
    end
end

app/helpers/algorithm_helper.rb
module AlgorithmHelper
end

app/helpers/algorithms_helper.rb
module AlgorithmsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_link_helper.rb
module HomeLinkHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relations_helper.rb
module RelationsHelper
end

app/views/acts_as_taggable_on/tags/_tag.html.erb
<style>
.tag {

  background: #eee;
  border-radius: 3px 0 0 3px;
  color: black;
  display: inline-block;
  height: 26px;
  line-height: 26px;
  padding: 0 20px 0 23px;
  position: relative;
  margin: 0 10px 10px 0;
  text-decoration: none;
  -webkit-transition: color 0.2s;
}

.tag::before {
  background: #fff;
  border-radius: 10px;
  box-shadow: inset 0 1px rgba(0, 0, 0, 0.25);
  content: '';
  height: 6px;
  left: 10px;
  position: absolute;
  width: 6px;
  top: 10px;
}

.tag::after {
  background: #fff;
  border-bottom: 13px solid transparent;
  border-left: 10px solid #eee;
  border-top: 13px solid transparent;
  content: '';
  position: absolute;
  right: 0;
  top: 0;
}

.tag:hover {
  background-color: crimson;
  color: white;
}

.tag:hover::after {
   border-left-color: crimson; 
}
</style>
<h4 class=tag><%= link_to tag.name, tag_path(tag) %></h4>

app/views/algorithm/index.html.erb
<h1><center>Algorithm Listing</center></h1>
<% if @algorithms.empty? %>
	<center>No algorithms matched your search</center>
<% else %>
	<% @algorithms.each do |alg| %>
		  <br>
			<center>
		  <h2><%= link_to alg.name, alg %></h2>
		  <%= sanitize alg.purpose %>
		  <h3> Difficulty: <span><%= alg.difficulty %></span></h3>
			</center>
		  </br>
	<% end %>
<% end %>

app/views/algorithms/_algorithm.html.erb
<h4 class=tag><%= link_to algorithm.name, algorithm_path(algorithm) %></h4>

app/views/algorithms/_form.html.erb
<%= form_for(@algorithm) do |f| %>
  <% if @algorithm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@algorithm.errors.count, "error") %> prohibited this algorithm from being saved:</h2>

      <ul>
      <% @algorithm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

	<div class="field">
    <%= f.label :purpose %><br>
    <%= f.text_field :purpose %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :pseudoCode %><br>
    <%= f.text_area :pseudoCode %>
  </div>
  <div class="field">
    <%= f.label :complexityAnalysis %><br>
    <%= f.text_area :complexityAnalysis %>
  </div>
  <div class="field">
    <%= f.label :difficulty %><br>
    <%= f.number_field :difficulty %>
  </div>

  <div class="field">
    <%= f.label :tag_list %><br>
    <%= f.text_field :tag_list %>
  </div>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/algorithms/_new.html.erb
<div class="row text-center">
  <%= form_for(Algorithm.new, remote: true) do |f| %>

    <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

	<div class="field">
    <%= f.label :purpose %><br>
    <%= f.text_field :purpose %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :pseudoCode %><br>
    <%= f.text_area :pseudoCode %>
  </div>
  <div class="field">
    <%= f.label :complexityAnalysis %><br>
    <%= f.text_area :complexityAnalysis %>
  </div>
  <div class="field">
    <%= f.label :difficulty %><br>
    <%= f.number_field :difficulty %>
  </div>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>



    <div class="large-10 large-centered columns">
      <%= f.text_field :all_tags, placeholder: "Tags separated with comma" %>
    </div>


  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>
</div>

app/views/algorithms/edit.html.erb
<h1>Editing algorithm</h1>

<%= render 'form' %>

<%= link_to 'Show', @algorithm %> |
<%= link_to 'Back', algorithms_path %>

app/views/algorithms/index.html.erb
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
<h1>Listing algorithms</h1>
<style>
table {
  border-collapse: collapse;
}
table tr, table th {
  border: 1px solid black;
}


</style>
<table>
	<th>Name</th>
    <th>Purpose</th> 
    <th>Description</th>	
	<th>Link</th>
    <th>Code</th> 
    <th>Complexity Analysis</th>
	<th>Difficulty</th>
    <th>Author</th>     
  <tbody>
    <% @algorithms.each do |algorithm| %>
      <tr>
        <td class="border_bottom"><%= algorithm.name %></td>
				<td class="border_bottom"><%= algorithm.purpose %></td>
        <td class="border_bottom"><%= algorithm.description[0...100] %>...</td>
        <td class="border_bottom"><%= algorithm.link %></td>
        <td class="border_bottom"><%= algorithm.pseudoCode[0...100] %>...</td>
        <td class="border_bottom"><%= algorithm.complexityAnalysis[0...100] %>...</td>
        <td class="border_bottom"><%= algorithm.difficulty %></td>
        <td class="border_bottom"><%= algorithm.author %></td>
	<!--<h1>Algorithms</h1>-->
	<!--<%= render @algorithms %>-->
        <td class='list_actions'>
  	<%= link_to 'Show', algorithm %><br/>
  	<%= link_to 'Edit', edit_algorithm_path(algorithm) %><br/>
  	<%= link_to 'Destroy', algorithm, method: :delete, 
      	data: { confirm: 'Are you sure?' } %>
</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Algorithm', new_algorithm_path %>

app/views/algorithms/new.html.erb
<h1>New algorithm</h1>

<%= render 'form' %>

<%= link_to 'Back', algorithms_path %>

app/views/algorithms/show.html.erb
<head>
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Roboto">
<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Tangerine">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.7.0/styles/default.min.css">
<script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js" type="text/javascript"></script>
<style>
     h1 {
      font-family: 'Roboto', serif;
      font-size: 48px;
     }
	span.fancy {
    color: red;
		font-family: 'Tangerine';
		font-size: 30px;
}

</style>
</head>

<!--<p id="notice"><%= notice %></p>-->

<p>
  <h1><center><%= @algorithm.name %></center></h1>
</p>

<br>
</br>

<center>
<h2>
  <strong>Purpose:</strong>
	<span class='italic'>
		<%= @algorithm.purpose %>
	</span>
</h2>
</center>

<br>
</br>
<h2>
  <strong><center>Description:</center></strong>
</h2>

<p>
<pre class="description">
  <%= @algorithm.description %>
</pre>
</p>

<p>
<center>
<img src=<%= @algorithm.link %> alt="Smiley face" height="400" width="400">
</center>
</p>


<h2 style="display: inline;">
  <strong><center>Pseudocode: <%= select_tag :code_language, options_for_select(Algorithm::ALGORITHM_LANGUAGES), :id => "code_language",:htm => { :style => 'display: inline;' } %></center></strong>
</h2>


<pre class="prettyprint">
<code>
	<div id="pseudoCode"><%= @algorithm.pseudoCode %></div>
	<div id="Python" style='display:none;'><%= @algorithm.Python %></div>
	<div id="Cpp" style='display:none;'><%= @algorithm.Cpp %></div>
	<div id="Java" style='display:none;'><%= @algorithm.Java %></div>
	<div id="Ruby" style='display:none;'><%= @algorithm.Ruby %></div>
</code>
</pre>

<h2>
  <strong><center>Complexity Analysis:</center></strong>
</h2>

<pre class="description">
  <%= @algorithm.complexityAnalysis %>
</pre>
<br></br>
<h3>
  <strong>Author's Difficulty: </strong><%= @algorithm.difficulty %>
</h3>

<h3>
  <strong>Author:</strong>
	<span class='fancy'>
		<%= @algorithm.author %>
	</span>
</h3>
<div style="font-size: 18px;"><%= render @algorithm.tags %></div>


<%= link_to 'Edit', edit_algorithm_path(@algorithm) %>
<%= link_to 'Back', algorithms_path %>


<script>
$(document).ready(function(){
    $('#code_language').change(function() {
			console.log(this.value)
      if(this.value == 'pseudoCode'){
				console.log('logged'+this.value)
        $("#pseudoCode").show();
				$("#Python").hide();
				$("#Java").hide();
				$("#Cpp").hide();
				$("#Ruby").hide();
      }
      else if(this.value == 'Python'){
				console.log('now logged'+this.value)
        $("#pseudoCode").hide();
				$("#Python").show();
				$("#Java").hide();
				$("#Cpp").hide();
				$("#Ruby").hide();
      }
			else if(this.value == 'Java'){
				$("#pseudoCode").hide();
				$("#Python").hide();
				$("#Java").show();
				$("#Cpp").hide();
				$("#Ruby").hide();
			}
			else if(this.value == 'Cpp'){
				$("#pseudoCode").hide();
				$("#Python").hide();
				$("#Java").hide();
				$("#Cpp").show();
				$("#Ruby").hide();
			}
			else if(this.value == 'Ruby'){
				$("#pseudoCode").hide();
				$("#Python").hide();
				$("#Java").hide();
				$("#Cpp").hide();
				$("#Ruby").show();
			}
    });
});
</script>

app/views/home_link/home.html.erb
<style>
	p{
		margin-left: 100px;
		margin-right: 100px;
	}
	h3{
		margin-left: 100px;
		margin-right: 100px;
	}
	h1{
		text-align: center;
	}
</style>
<h1>Welcome!</h1>
<p style="font-size: 18px;">Welcome to the home page of the Algorithm Tutorial site. The plan is for this site contain interesting articles regarding computer science and mathematics. It is targeted towards anyone who is interested in implementing and understanding algorithms. The site has an index listing every available algorithm. Currently there are 3 main categories of algorihtm: sorting, searching and optimisation. If you would like to contribute, contact d.smyth10@nuigalway.ie Happy browsing! </p>

<p><h3>Algorithm of the Day: <%= link_to Algorithm.find((Time.now.strftime("%d%m%Y").to_i%Algorithm.count)+1).name, algorithm_path(Algorithm.find((Time.now.strftime("%d%m%Y").to_i%Algorithm.count)+1)) %> </h3>

</p>

app/views/homes/show.html.erb
<h1>Homes#show</h1>
<p>Find me in app/views/homes/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>AlgorithmTutorial</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
<body>

<%= content_tag :body, class: controller.controller_name do %>
<div id="banner" style="height:60px;">
	<%= @page_title || "BlackBored" %>
	<%= image_tag "Cog.jpg", :size => "60x60" %>
</div>
  <div>
  	<nav id="navigationbar">
    	<ul>
				<li><%= link_to 'Home', home_path %></li>
 	      <li><%= link_to 'Algorithms Index', index_path %></li>
        <li><%= link_to "Edit Algorithms", algorithms_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
			<%= form_tag(index_path, :method => "get", id: "search-form") do %>
			<%= text_field_tag :search, params[:search], placeholder: "Search Algorithms" %>
			<%= submit_tag "Search" %>
			<% end %>
    </nav>
	</div>
  <div id="main">
    <%= yield %>
  </div>
<% end %>
</div>
</body>
</html>

app/views/relations/_form.html.erb
<%= form_for(@relation) do |f| %>
  <% if @relation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relation.errors.count, "error") %> prohibited this relation from being saved:</h2>

      <ul>
      <% @relation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :algorithms_id %><br>
    <%= f.text_field :algorithms_id %>
  </div>
  <div class="field">
    <%= f.label :inventor %><br>
    <%= f.text_field :inventor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/relations/edit.html.erb
<h1>Editing relation</h1>

<%= render 'form' %>

<%= link_to 'Show', @relation %> |
<%= link_to 'Back', relations_path %>

app/views/relations/index.html.erb
<h1>Listing relations</h1>

<table>
  <thead>
    <tr>
      <th>Algorithms</th>
      <th>Inventor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @relations.each do |relation| %>
      <tr>
        <td><%= relation.algorithms %></td>
        <td><%= relation.inventor %></td>
        <td><%= link_to 'Show', relation %></td>
        <td><%= link_to 'Edit', edit_relation_path(relation) %></td>
        <td><%= link_to 'Destroy', relation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Relation', new_relation_path %>

app/views/relations/new.html.erb
<h1>New relation</h1>

<%= render 'form' %>

<%= link_to 'Back', relations_path %>

app/views/relations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Algorithms:</strong>
  <%= @relation.algorithms %>
</p>

<p>
  <strong>Inventor:</strong>
  <%= @relation.inventor %>
</p>

<%= link_to 'Edit', edit_relation_path(@relation) %> |
<%= link_to 'Back', relations_path %>

app/views/tags/_form.html.erb
<%= form_for(@tag,url: tag_path,method: :put) do |f| %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>
<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Tags</h1>
<%= render @tags %>

app/views/tags/show.html.erb
<%= stylesheet_link_tag "application", :media => "all" %>
<style>
	h1{
		text-align: center;
	}
	div{
		text-align: center;
	}
.tag {
  border-radius: 3px 0 0 3px;
  color: black;
  display: inline-block;
  height: 26px;
  line-height: 26px;
  padding: 0 20px 0 23px;
  position: relative;
  margin: 0 10px 10px 0;
  text-decoration: none;
  -webkit-transition: color 0.2s;
}

.tag::before {
  background: #fff;	
	background-color: white;
  border-radius: 10px;
  box-shadow: inset 0 1px rgba(0, 0, 0, 0.25);
  content: '';
  height: 6px;
  left: 10px;
  position: absolute;
  width: 6px;
  top: 10px;
}

.tag::after {
  background: #fff;
  border-bottom: 13px solid transparent;
  border-left: 10px solid #eee;
  border-top: 13px solid transparent;
  content: '';
  position: absolute;
  right: 0;
  top: 0;
}

.tag:hover {
  background-color: crimson;
  color: white;
}

.tag:hover::after {
   border-left-color: crimson; 
}
pre{
	text-align: left;
	background: white;
	font-size: 13px;
}
</style>

<body>
<h1><%= @tag.name %></h1>
<pre>
<%= @tag.description %>
</pre>
<br>
<br>
<h2>Algorithms which have been tagged with <%= @tag.name %>:</h2>
<div style="font-size: 18px;"><%= render @algorithms %></div>
<body>
<%= link_to 'Edit', edit_tag_path(@tag) %>